#Use ubuntu 14:04 as main OS
FROM ubuntu:14.04

#Install packages
RUN  apt-get update &&  apt-get install -y	\
			gcc			\
			libconfig-dev		\
			make			\
       			bash            	\
			vim			\
			git			\
			build-essential		

